//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProje.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class adres
    {
        public byte id { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public string adres1 { get; set; }
        public string konum { get; set; }
    }
}
